const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('api', {
  // Electron 32 removed File.path — this is the supported way to get a dropped file's path
  getFilePath: (file) => webUtils.getPathForFile(file),
  loadData: () => ipcRenderer.invoke('data:load'),
  saveData: (data) => ipcRenderer.invoke('data:save', data),
  pickFiles: () => ipcRenderer.invoke('file:pick'),
  openFile: (filePath) => ipcRenderer.invoke('file:open', filePath),
  copyToLibrary: (srcPath) => ipcRenderer.invoke('file:copy-to-library', srcPath),
  readFileBinary: (filePath) => ipcRenderer.invoke('file:read-binary', filePath),
  fileExists: (filePath) => ipcRenderer.invoke('file:exists', filePath),
  importFolderTree: (folderPath) => ipcRenderer.invoke('folder:import-tree', folderPath),
  importFolderAll: (folderPath) => ipcRenderer.invoke('folder:import-all', folderPath),
  importFolderDeck: (folderPath) => ipcRenderer.invoke('folder:import-deck', folderPath),
  pickFolder: () => ipcRenderer.invoke('folder:pick'),
  isDirectory: (p) => ipcRenderer.invoke('path:is-directory', p),
  exportReport: (filename, content) => ipcRenderer.invoke('report:export', { filename, content }),
  copyToClipboard: (text) => ipcRenderer.invoke('clipboard:write', text),
  openExternal: (url) => ipcRenderer.invoke('shell:open-external', url),
  revealInFinder: (p) => ipcRenderer.invoke('shell:reveal', p),
  createHomeworkFolder: (payload) => ipcRenderer.invoke('homework:create-folder', payload),
  zoomTest: (creds) => ipcRenderer.invoke('zoom:test', creds),
  zoomCreateMeeting: (payload) => ipcRenderer.invoke('zoom:create-meeting', payload),
  zoomDeleteMeeting: (payload) => ipcRenderer.invoke('zoom:delete-meeting', payload),
  checkApps: () => ipcRenderer.invoke('app:check-apps'),
  openWith: (filePath, appName) => ipcRenderer.invoke('file:open-with', { filePath, appName }),
  hasLibreOffice: () => ipcRenderer.invoke('app:has-libreoffice'),
  htmlHasIndex: (folderPath) => ipcRenderer.invoke('html:has-index', folderPath),
  importHtmlFolder: (folderPath) => ipcRenderer.invoke('html:import-folder', folderPath),
  convertPptxToPdf: (pptxPath) => ipcRenderer.invoke('pptx:convert-pdf', pptxPath),
})
